%BeginHeader

The description of your items:

- There are 4 practice trials. Added to make sure the subject understands the task and to establish a baseline.
- There are 2 subexperiments.  Items 1-40 (conditions 1-2) are prepositional dative sentences; condition 1 is grammatical, condition 2 has a missing
word (to).  Items 41-80 (conditions 3-4) are sentences with complex subject; condition 3 is grammatical (the keys to the cabinets are), condition 4
has singular subject, so agreement error (the key to the cabinets are).  For both of these experiments, all items are followed by 'was there anything
wrong with that sentence.'
- There are 100 filler sentences(items 81-180), all condition 5. Each of these filler sentences has a comprehension question after it.

Use Monaco font 10 point
Display 1024 x 768

%EndHeader

set conditions =  2
set experiments = 3
set expConditions = 2 2 1
set background =  16777215
set foreground =  0
set filterMode = 2
set windowThreshold = 0
set calibration_type = 0
set calibration_height = 1482170400
set display_type = LCD

trial_type question
  text_format =    'Monaco' 10 24 18 263 nonantialiased
  text_weight =    normal non-italic
  button =         leftTrigger
  button =         rightTrigger
  output =         nostream
  trigger =        nogaze
  cursor_size =    0
  dc_delay =       0
  stimulus_delay = 0
  revert =         0
  highlight_color =262402
end question

trial_type sentence
  text_format =    'Monaco' 10 24 18 263 nonantialiased
  text_weight =    normal non-italic
  button =         rightTrigger
  output =         stream
  trigger =        driftandgaze
  cursor_size =    0
  dc_delay =       0
  stimulus_delay = 0
  revert =         0
  highlight_color =262402
end sentence

trial P99I900D0
  gc_rect =          (0 0 0 0)
  inline =           |The Red Sox beat the Yankees last night.\n
  max_display_time = 1500000
  trial_type =       sentence
end P99I900D0

trial P99I905D0
  gc_rect =          (0 0 0 0)
  inline =           |An important question is how visual attention is spatially distributed across multi-modalities.\n
  max_display_time = 1500000
  trial_type =       sentence
end P99I905D0

trial P99I906D0
  gc_rect =          (0 0 0 0)
  inline =           |Rembrandt is considered the greatest Dutch painter of all time.\n
  max_display_time = 1500000
  trial_type =       sentence
end P99I906D0

trial P99I907D0
  gc_rect =          (0 0 0 0)
  inline =           |The moose showed up on campus during the football game.\n
  max_display_time = 1500000
  trial_type =       sentence
end P99I907D0

trial E1I1D0
  gc_rect =          (0 0 0 0)
  inline =           |As soon as the meeting ended, Paul gave the project files to his assistant, eager to wrap up the day's tasks.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I1D0

trial E2I1D0
  gc_rect =          (0 0 0 0)
  inline =           |As soon as the meeting ended, Paul gave the project files his assistant, eager to wrap up the day's tasks.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I1D0

trial E102I1D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I1D1

trial E103I1D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I1D1

trial E1I2D0
  gc_rect =          (0 0 0 0)
  inline =           |Unsure whether it was the right decision, Mia sold her furniture to a local dealer before moving out of her old apartment.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I2D0

trial E2I2D0
  gc_rect =          (0 0 0 0)
  inline =           |Unsure whether it was the right decision, Mia sold her furniture a local dealer before moving out of her old apartment.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I2D0

trial E102I2D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I2D1

trial E103I2D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I2D1

trial E1I3D0
  gc_rect =          (0 0 0 0)
  inline =           |Without waiting for a reply, Alan showed his portfolio to the hiring manager and moved on to the next part of the interview.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I3D0

trial E2I3D0
  gc_rect =          (0 0 0 0)
  inline =           |Without waiting for a reply, Alan showed his portfolio the hiring manager and moved on to the next part of the interview.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I3D0

trial E102I3D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I3D1

trial E103I3D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I3D1

trial E1I4D0
  gc_rect =          (0 0 0 0)
  inline =           |I was surprised when I heard that Mark had given his collection of vintage records to his cousin as a birthday present.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I4D0

trial E2I4D0
  gc_rect =          (0 0 0 0)
  inline =           |I was surprised when I heard that Mark had given his collection of vintage records his cousin as a birthday present.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I4D0

trial E102I4D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I4D1

trial E103I4D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I4D1

trial E1I5D0
  gc_rect =          (0 0 0 0)
  inline =           |Realizing he wouldn't use it anymore, Lucas sold his gaming console to his neighbor, hoping to make a bit of extra cash.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I5D0

trial E2I5D0
  gc_rect =          (0 0 0 0)
  inline =           |Realizing he wouldn't use it anymore, Lucas sold his gaming console his neighbor, hoping to make a bit of extra cash.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I5D0

trial E102I5D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I5D1

trial E103I5D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I5D1

trial E1I6D0
  gc_rect =          (0 0 0 0)
  inline =           |After finishing her shift, Emily handed the documents to her supervisor and hurried out of the office.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I6D0

trial E2I6D0
  gc_rect =          (0 0 0 0)
  inline =           |After finishing her shift, Emily handed the documents her supervisor and hurried out of the office.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I6D0

trial E102I6D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I6D1

trial E103I6D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I6D1

trial E1I7D0
  gc_rect =          (0 0 0 0)
  inline =           |Without thinking twice, Michael tossed his keys to his roommate before heading out for the weekend.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I7D0

trial E2I7D0
  gc_rect =          (0 0 0 0)
  inline =           |Without thinking twice, Michael tossed his keys his roommate before heading out for the weekend.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I7D0

trial E102I7D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I7D1

trial E103I7D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I7D1

trial E1I8D0
  gc_rect =          (0 0 0 0)
  inline =           |Although the weather was terrible, Sarah delivered a package to the neighbors and then went inside to warm up.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I8D0

trial E2I8D0
  gc_rect =          (0 0 0 0)
  inline =           |Although the weather was terrible, Sarah delivered a package the neighbors and then went inside to warm up.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I8D0

trial E102I8D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I8D1

trial E103I8D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I8D1

trial E1I9D0
  gc_rect =          (0 0 0 0)
  inline =           |Before the event started, the coach distributed the team jerseys to the players and explained the game plan.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I9D0

trial E2I9D0
  gc_rect =          (0 0 0 0)
  inline =           |Before the event started, the coach distributed the team jerseys the players and explained the game plan.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I9D0

trial E102I9D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I9D1

trial E103I9D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I9D1

trial E1I10D0
  gc_rect =          (0 0 0 0)
  inline =           |After weeks of planning, Jessica finally presented the proposal to the board members, confident they would approve it.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I10D0

trial E2I10D0
  gc_rect =          (0 0 0 0)
  inline =           |After weeks of planning, Jessica finally presented the proposal the board members, confident they would approve it.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I10D0

trial E102I10D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I10D1

trial E103I10D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I10D1

trial E1I11D0
  gc_rect =          (0 0 0 0)
  inline =           |As the concert came to an end, the singer threw a signed poster to the audience, which caused a frenzy among the fans.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I11D0

trial E2I11D0
  gc_rect =          (0 0 0 0)
  inline =           |As the concert came to an end, the singer threw a signed poster the audience, which caused a frenzy among the fans.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I11D0

trial E102I11D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I11D1

trial E103I11D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I11D1

trial E1I12D0
  gc_rect =          (0 0 0 0)
  inline =           |The teacher always makes sure to explain the new concepts to the students before assigning the homework.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I12D0

trial E2I12D0
  gc_rect =          (0 0 0 0)
  inline =           |The teacher always makes sure to explain the new concepts the students before assigning the homework.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I12D0

trial E102I12D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I12D1

trial E103I12D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I12D1

trial E1I13D0
  gc_rect =          (0 0 0 0)
  inline =           |While reviewing his monthly expenses, Jason realized he had sent money to the wrong account and quickly contacted the bank.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I13D0

trial E2I13D0
  gc_rect =          (0 0 0 0)
  inline =           |While reviewing his monthly expenses, Jason realized he had sent money the wrong account and quickly contacted the bank.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I13D0

trial E102I13D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I13D1

trial E103I13D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I13D1

trial E1I14D0
  gc_rect =          (0 0 0 0)
  inline =           |Late at night, the teacher emailed the assignment to her students, reminding them of the deadline the next day.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I14D0

trial E2I14D0
  gc_rect =          (0 0 0 0)
  inline =           |Late at night, the teacher emailed the assignment her students, reminding them of the deadline the next day.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I14D0

trial E102I14D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I14D1

trial E103I14D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I14D1

trial E1I15D0
  gc_rect =          (0 0 0 0)
  inline =           |I didn't realize that Paul had given his old books to the library until I saw them on the donation shelf.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I15D0

trial E2I15D0
  gc_rect =          (0 0 0 0)
  inline =           |I didn't realize that Paul had given his old books the library until I saw them on the donation shelf.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I15D0

trial E102I15D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I15D1

trial E103I15D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I15D1

trial E1I16D0
  gc_rect =          (0 0 0 0)
  inline =           |To lighten her load, Rebecca sold her furniture to a neighbor, planning to travel abroad with just a suitcase.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I16D0

trial E2I16D0
  gc_rect =          (0 0 0 0)
  inline =           |To lighten her load, Rebecca sold her furniture a neighbor, planning to travel abroad with just a suitcase.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I16D0

trial E102I16D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I16D1

trial E103I16D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I16D1

trial E1I17D0
  gc_rect =          (0 0 0 0)
  inline =           |Before the meeting began, David showed the latest report to his boss, eager to hear feedback.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I17D0

trial E2I17D0
  gc_rect =          (0 0 0 0)
  inline =           |Before the meeting began, David showed the latest report his boss, eager to hear feedback.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I17D0

trial E102I17D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I17D1

trial E103I17D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I17D1

trial E1I18D0
  gc_rect =          (0 0 0 0)
  inline =           |By the end of the week, I had mailed the documents to the lawyer, hoping the matter would be resolved quickly.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I18D0

trial E2I18D0
  gc_rect =          (0 0 0 0)
  inline =           |By the end of the week, I had mailed the documents the lawyer, hoping the matter would be resolved quickly.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I18D0

trial E102I18D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I18D1

trial E103I18D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I18D1

trial E1I19D0
  gc_rect =          (0 0 0 0)
  inline =           |Hoping to seal the deal, the real estate agent showed the property to a group of potential buyers at sunset.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I19D0

trial E2I19D0
  gc_rect =          (0 0 0 0)
  inline =           |Hoping to seal the deal, the real estate agent showed the property a group of potential buyers at sunset.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I19D0

trial E102I19D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I19D1

trial E103I19D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I19D1

trial E1I20D0
  gc_rect =          (0 0 0 0)
  inline =           |The instructor promised extra help and later explained the difficult concept to her struggling student in the afternoon.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I20D0

trial E2I20D0
  gc_rect =          (0 0 0 0)
  inline =           |The instructor promised extra help and later explained the difficult concept her struggling student in the afternoon.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I20D0

trial E102I20D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I20D1

trial E103I20D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I20D1

trial E1I21D0
  gc_rect =          (0 0 0 0)
  inline =           |As part of her morning routine, the teacher read a story to the children while they sat quietly on the carpet.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I21D0

trial E2I21D0
  gc_rect =          (0 0 0 0)
  inline =           |As part of her morning routine, the teacher read a story the children while they sat quietly on the carpet.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I21D0

trial E102I21D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I21D1

trial E103I21D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I21D1

trial E1I22D0
  gc_rect =          (0 0 0 0)
  inline =           |After finishing his workout, Greg tossed the ball to his friend before heading home for dinner.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I22D0

trial E2I22D0
  gc_rect =          (0 0 0 0)
  inline =           |After finishing his workout, Greg tossed the ball his friend before heading home for dinner.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I22D0

trial E102I22D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I22D1

trial E103I22D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I22D1

trial E1I23D0
  gc_rect =          (0 0 0 0)
  inline =           |Sarah eagerly showed the photograph to her parents when she returned from her trip to Italy.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I23D0

trial E2I23D0
  gc_rect =          (0 0 0 0)
  inline =           |Sarah eagerly showed the photograph her parents when she returned from her trip to Italy.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I23D0

trial E102I23D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I23D1

trial E103I23D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I23D1

trial E1I24D0
  gc_rect =          (0 0 0 0)
  inline =           |To improve customer relations, the company offered a discount to its loyal clients during the holiday season.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I24D0

trial E2I24D0
  gc_rect =          (0 0 0 0)
  inline =           |To improve customer relations, the company offered a discount its loyal clients during the holiday season.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I24D0

trial E102I24D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I24D1

trial E103I24D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I24D1

trial E1I25D0
  gc_rect =          (0 0 0 0)
  inline =           |Jake delivered a letter to his boss before rushing out of the office to catch his train.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I25D0

trial E2I25D0
  gc_rect =          (0 0 0 0)
  inline =           |Jake delivered a letter his boss before rushing out of the office to catch his train.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I25D0

trial E102I25D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I25D1

trial E103I25D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I25D1

trial E1I26D0
  gc_rect =          (0 0 0 0)
  inline =           |In a rush to catch the train, Alex tossed his jacket to his friend, hoping to retrieve it later.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I26D0

trial E2I26D0
  gc_rect =          (0 0 0 0)
  inline =           |In a rush to catch the train, Alex tossed his jacket his friend, hoping to retrieve it later.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I26D0

trial E102I26D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I26D1

trial E103I26D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I26D1

trial E1I27D0
  gc_rect =          (0 0 0 0)
  inline =           |Without saying a word, Sarah passed the note to her colleague during the meeting.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I27D0

trial E2I27D0
  gc_rect =          (0 0 0 0)
  inline =           |Without saying a word, Sarah passed the note her colleague during the meeting.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I27D0

trial E102I27D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I27D1

trial E103I27D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I27D1

trial E1I28D0
  gc_rect =          (0 0 0 0)
  inline =           |The artist showed her latest painting to a group of investors at the gallery's opening night.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I28D0

trial E2I28D0
  gc_rect =          (0 0 0 0)
  inline =           |The artist showed her latest painting a group of investors at the gallery's opening night.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I28D0

trial E102I28D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I28D1

trial E103I28D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I28D1

trial E1I29D0
  gc_rect =          (0 0 0 0)
  inline =           |The little boy proudly handed his drawing to the teacher, eager for her praise.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I29D0

trial E2I29D0
  gc_rect =          (0 0 0 0)
  inline =           |The little boy proudly handed his drawing the teacher, eager for her praise.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I29D0

trial E102I29D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I29D1

trial E103I29D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I29D1

trial E1I30D0
  gc_rect =          (0 0 0 0)
  inline =           |My cousin sold his vintage camera to a photography enthusiast, eager to clear space in his studio.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I30D0

trial E2I30D0
  gc_rect =          (0 0 0 0)
  inline =           |My cousin sold his vintage camera a photography enthusiast, eager to clear space in his studio.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I30D0

trial E102I30D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I30D1

trial E103I30D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I30D1

trial E1I31D0
  gc_rect =          (0 0 0 0)
  inline =           |I didn't realize that Tom tossed the ball to his dog until it was too late and it hit the window.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I31D0

trial E2I31D0
  gc_rect =          (0 0 0 0)
  inline =           |I didn't realize that Tom tossed the ball his dog until it was too late and it hit the window.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I31D0

trial E102I31D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I31D1

trial E103I31D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I31D1

trial E1I32D0
  gc_rect =          (0 0 0 0)
  inline =           |As the meeting ended, she forwarded the agenda to her manager, ensuring he was informed before the next discussion.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I32D0

trial E2I32D0
  gc_rect =          (0 0 0 0)
  inline =           |As the meeting ended, she forwarded the agenda her manager, ensuring he was informed before the next discussion.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I32D0

trial E102I32D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I32D1

trial E103I32D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I32D1

trial E1I33D0
  gc_rect =          (0 0 0 0)
  inline =           |The author read a passage from her book to the audience at the bookstore's grand opening.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I33D0

trial E2I33D0
  gc_rect =          (0 0 0 0)
  inline =           |The author read a passage from her book the audience at the bookstore's grand opening.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I33D0

trial E102I33D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I33D1

trial E103I33D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I33D1

trial E1I34D0
  gc_rect =          (0 0 0 0)
  inline =           |Hoping to catch the last train, Joe rushed to the station and handed his ticket to the conductor with seconds to spare.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I34D0

trial E2I34D0
  gc_rect =          (0 0 0 0)
  inline =           |Hoping to catch the last train, Joe rushed to the station and handed his ticket the conductor with seconds to spare.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I34D0

trial E102I34D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I34D1

trial E103I34D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I34D1

trial E1I35D0
  gc_rect =          (0 0 0 0)
  inline =           |During the charity event, they sold homemade crafts to the attendees, raising funds for the community center.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I35D0

trial E2I35D0
  gc_rect =          (0 0 0 0)
  inline =           |During the charity event, they sold homemade crafts the attendees, raising funds for the community center.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I35D0

trial E102I35D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I35D1

trial E103I35D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I35D1

trial E1I36D0
  gc_rect =          (0 0 0 0)
  inline =           |After finishing the presentation, Sarah offered a suggestion to the committee in hopes of improving the project's timeline.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I36D0

trial E2I36D0
  gc_rect =          (0 0 0 0)
  inline =           |After finishing the presentation, Sarah offered a suggestion the committee in hopes of improving the project's timeline.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I36D0

trial E102I36D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I36D1

trial E103I36D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I36D1

trial E1I37D0
  gc_rect =          (0 0 0 0)
  inline =           |Once the package arrived, I shipped a replacement part to the customer and apologized for the inconvenience.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I37D0

trial E2I37D0
  gc_rect =          (0 0 0 0)
  inline =           |Once the package arrived, I shipped a replacement part the customer and apologized for the inconvenience.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I37D0

trial E102I37D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I37D1

trial E103I37D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I37D1

trial E1I38D0
  gc_rect =          (0 0 0 0)
  inline =           |Even though it was late, David sent a message to his boss to confirm the next morning's meeting details.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I38D0

trial E2I38D0
  gc_rect =          (0 0 0 0)
  inline =           |Even though it was late, David sent a message his boss to confirm the next morning's meeting details.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I38D0

trial E102I38D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I38D1

trial E103I38D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I38D1

trial E1I39D0
  gc_rect =          (0 0 0 0)
  inline =           |I was surprised when David showed the project files to the client without asking for approval first.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I39D0

trial E2I39D0
  gc_rect =          (0 0 0 0)
  inline =           |I was surprised when David showed the project files the client without asking for approval first.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I39D0

trial E102I39D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I39D1

trial E103I39D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I39D1

trial E1I40D0
  gc_rect =          (0 0 0 0)
  inline =           |The company transferred the ownership rights to the new investor after completing the merger last quarter.\n
  max_display_time = 20000
  trial_type =       sentence
end E1I40D0

trial E2I40D0
  gc_rect =          (0 0 0 0)
  inline =           |The company transferred the ownership rights the new investor after completing the merger last quarter.\n
  max_display_time = 20000
  trial_type =       sentence
end E2I40D0

trial E102I40D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I40D1

trial E103I40D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I40D1

trial E3I41D0
  gc_rect =          (0 0 0 0)
  inline =           |The doors to the rooms are locked at night.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I41D0

trial E4I41D0
  gc_rect =          (0 0 0 0)
  inline =           |The door to the rooms are locked at night.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I41D0

trial E102I41D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I41D1

trial E103I41D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I41D1

trial E3I42D0
  gc_rect =          (0 0 0 0)
  inline =           |The schedules for the meetings are posted in the lobby.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I42D0

trial E4I42D0
  gc_rect =          (0 0 0 0)
  inline =           |The schedule for the meetings are posted in the lobby.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I42D0

trial E102I42D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I42D1

trial E103I42D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I42D1

trial E3I43D0
  gc_rect =          (0 0 0 0)
  inline =           |The recipes for the cakes are written in the cookbook.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I43D0

trial E4I43D0
  gc_rect =          (0 0 0 0)
  inline =           |The recipe for the cakes are written in the cookbook.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I43D0

trial E102I43D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I43D1

trial E103I43D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I43D1

trial E3I44D0
  gc_rect =          (0 0 0 0)
  inline =           |The paths through the woods are covered with snow.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I44D0

trial E4I44D0
  gc_rect =          (0 0 0 0)
  inline =           |The path through the woods are covered with snow.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I44D0

trial E102I44D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I44D1

trial E103I44D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I44D1

trial E3I45D0
  gc_rect =          (0 0 0 0)
  inline =           |The explanations for the accidents are unclear to the investigators.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I45D0

trial E4I45D0
  gc_rect =          (0 0 0 0)
  inline =           |The explanation for the accidents are unclear to the investigators.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I45D0

trial E102I45D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I45D1

trial E103I45D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I45D1

trial E3I46D0
  gc_rect =          (0 0 0 0)
  inline =           |The designs of the houses are unique in this neighborhood.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I46D0

trial E4I46D0
  gc_rect =          (0 0 0 0)
  inline =           |The design of the houses are unique in this neighborhood.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I46D0

trial E102I46D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I46D1

trial E103I46D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I46D1

trial E3I47D0
  gc_rect =          (0 0 0 0)
  inline =           |The titles of the essays are written in bold on the first page.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I47D0

trial E4I47D0
  gc_rect =          (0 0 0 0)
  inline =           |The title of the essays are written in bold on the first page.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I47D0

trial E102I47D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I47D1

trial E103I47D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I47D1

trial E3I48D0
  gc_rect =          (0 0 0 0)
  inline =           |The shapes of the sculptures are admired by art critics around the world.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I48D0

trial E4I48D0
  gc_rect =          (0 0 0 0)
  inline =           |The shape of the sculptures are admired by art critics around the world.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I48D0

trial E102I48D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I48D1

trial E103I48D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I48D1

trial E3I49D0
  gc_rect =          (0 0 0 0)
  inline =           |The sounds of the engines are echoing through the entire building.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I49D0

trial E4I49D0
  gc_rect =          (0 0 0 0)
  inline =           |The sound of the engines are echoing through the entire building.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I49D0

trial E102I49D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I49D1

trial E103I49D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I49D1

trial E3I50D0
  gc_rect =          (0 0 0 0)
  inline =           |The directors of the movies were praised for their artistic vision.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I50D0

trial E4I50D0
  gc_rect =          (0 0 0 0)
  inline =           |The director of the movies were praised for their artistic vision.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I50D0

trial E102I50D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I50D1

trial E103I50D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I50D1

trial E3I51D0
  gc_rect =          (0 0 0 0)
  inline =           |The messages from the teachers are being broadcast to all students.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I51D0

trial E4I51D0
  gc_rect =          (0 0 0 0)
  inline =           |The message from the teachers are being broadcast to all students.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I51D0

trial E102I51D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I51D1

trial E103I51D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I51D1

trial E3I52D0
  gc_rect =          (0 0 0 0)
  inline =           |The editors of the magazines are reviewing the articles before publication.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I52D0

trial E4I52D0
  gc_rect =          (0 0 0 0)
  inline =           |The editor of the magazines are reviewing the articles before publication.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I52D0

trial E102I52D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I52D1

trial E103I52D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I52D1

trial E3I53D0
  gc_rect =          (0 0 0 0)
  inline =           |The owners of the cafes are introducing a new menu next month.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I53D0

trial E4I53D0
  gc_rect =          (0 0 0 0)
  inline =           |The owner of the cafes are introducing a new menu next month.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I53D0

trial E102I53D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I53D1

trial E103I53D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I53D1

trial E3I54D0
  gc_rect =          (0 0 0 0)
  inline =           |The painters of the murals are planning a new piece for the downtown area.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I54D0

trial E4I54D0
  gc_rect =          (0 0 0 0)
  inline =           |The painter of the murals are planning a new piece for the downtown area.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I54D0

trial E102I54D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I54D1

trial E103I54D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I54D1

trial E3I55D0
  gc_rect =          (0 0 0 0)
  inline =           |The descriptions of the products are listed on the packaging.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I55D0

trial E4I55D0
  gc_rect =          (0 0 0 0)
  inline =           |The description of the products are listed on the packaging.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I55D0

trial E102I55D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I55D1

trial E103I55D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I55D1

trial E3I56D0
  gc_rect =          (0 0 0 0)
  inline =           |The origins of the rumors are still unclear to the public.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I56D0

trial E4I56D0
  gc_rect =          (0 0 0 0)
  inline =           |The origin of the rumors are still unclear to the public.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I56D0

trial E102I56D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I56D1

trial E103I56D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I56D1

trial E3I57D0
  gc_rect =          (0 0 0 0)
  inline =           |The melodies of the tunes are playing softly in the background.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I57D0

trial E4I57D0
  gc_rect =          (0 0 0 0)
  inline =           |The melody of the tunes are playing softly in the background.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I57D0

trial E102I57D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I57D1

trial E103I57D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I57D1

trial E3I58D0
  gc_rect =          (0 0 0 0)
  inline =           |The styles of the paintings are unique to this artist.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I58D0

trial E4I58D0
  gc_rect =          (0 0 0 0)
  inline =           |The style of the paintings are unique to this artist.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I58D0

trial E102I58D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I58D1

trial E103I58D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I58D1

trial E3I59D0
  gc_rect =          (0 0 0 0)
  inline =           |The sparkles of the jewels are catching everyone's attention.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I59D0

trial E4I59D0
  gc_rect =          (0 0 0 0)
  inline =           |The sparkle of the jewels are catching everyone's attention.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I59D0

trial E102I59D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I59D1

trial E103I59D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I59D1

trial E3I60D0
  gc_rect =          (0 0 0 0)
  inline =           |The formations of the clouds are changing with the wind.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I60D0

trial E4I60D0
  gc_rect =          (0 0 0 0)
  inline =           |The formation of the clouds are changing with the wind.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I60D0

trial E102I60D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I60D1

trial E103I60D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I60D1

trial E3I61D0
  gc_rect =          (0 0 0 0)
  inline =           |In the distance, the lights in the buildings are barely visible.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I61D0

trial E4I61D0
  gc_rect =          (0 0 0 0)
  inline =           |In the distance, the light in the buildings are barely visible.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I61D0

trial E102I61D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I61D1

trial E103I61D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I61D1

trial E3I62D0
  gc_rect =          (0 0 0 0)
  inline =           |After a brief introduction, the leaders of the tours are ready to start the trip.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I62D0

trial E4I62D0
  gc_rect =          (0 0 0 0)
  inline =           |After a brief introduction, the leader of the tours are ready to start the trip.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I62D0

trial E102I62D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I62D1

trial E103I62D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I62D1

trial E3I63D0
  gc_rect =          (0 0 0 0)
  inline =           |After the long meeting, the keys to the cabinets are still missing from the office.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I63D0

trial E4I63D0
  gc_rect =          (0 0 0 0)
  inline =           |After the long meeting, the key to the cabinets are still missing from the office.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I63D0

trial E102I63D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I63D1

trial E103I63D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I63D1

trial E3I64D0
  gc_rect =          (0 0 0 0)
  inline =           |In the early morning hours, the colors of the curtains were barely noticeable.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I64D0

trial E4I64D0
  gc_rect =          (0 0 0 0)
  inline =           |In the early morning hours, the color of the curtains were barely noticeable.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I64D0

trial E102I64D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I64D1

trial E103I64D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I64D1

trial E3I65D0
  gc_rect =          (0 0 0 0)
  inline =           |Despite the confusion, the decisions about the changes are expected by tomorrow.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I65D0

trial E4I65D0
  gc_rect =          (0 0 0 0)
  inline =           |Despite the confusion, the decision about the changes are expected by tomorrow.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I65D0

trial E102I65D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I65D1

trial E103I65D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I65D1

trial E3I66D0
  gc_rect =          (0 0 0 0)
  inline =           |At the end of the day, the captains of the ships were finally satisfied with the plans.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I66D0

trial E4I66D0
  gc_rect =          (0 0 0 0)
  inline =           |At the end of the day, the captain of the ships were finally satisfied with the plans.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I66D0

trial E102I66D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I66D1

trial E103I66D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I66D1

trial E3I67D0
  gc_rect =          (0 0 0 0)
  inline =           |Following the latest update, the prices of the tickets are set to increase next week.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I67D0

trial E4I67D0
  gc_rect =          (0 0 0 0)
  inline =           |Following the latest update, the price of the tickets are set to increase next week.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I67D0

trial E102I67D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I67D1

trial E103I67D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I67D1

trial E3I68D0
  gc_rect =          (0 0 0 0)
  inline =           |After several delays, the managers of the projects were eventually called in for a meeting.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I68D0

trial E4I68D0
  gc_rect =          (0 0 0 0)
  inline =           |After several delays, the manager of the projects were eventually called in for a meeting.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I68D0

trial E102I68D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I68D1

trial E103I68D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I68D1

trial E3I69D0
  gc_rect =          (0 0 0 0)
  inline =           |On such short notice, the authors of the novels are doing an impromptu reading session.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I69D0

trial E4I69D0
  gc_rect =          (0 0 0 0)
  inline =           |On such short notice, the author of the novels are doing an impromptu reading session.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I69D0

trial E102I69D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I69D1

trial E103I69D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I69D1

trial E3I70D0
  gc_rect =          (0 0 0 0)
  inline =           |During the discussion, the solutions to the problems were brought up several times.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I70D0

trial E4I70D0
  gc_rect =          (0 0 0 0)
  inline =           |During the discussion, the solution to the problems were brought up several times.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I70D0

trial E102I70D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I70D1

trial E103I70D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I70D1

trial E3I71D0
  gc_rect =          (0 0 0 0)
  inline =           |Late in the afternoon, the reports on the findings are distributed to the attendees.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I71D0

trial E4I71D0
  gc_rect =          (0 0 0 0)
  inline =           |Late in the afternoon, the report on the findings are distributed to the attendees.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I71D0

trial E102I71D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I71D1

trial E103I71D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I71D1

trial E3I72D0
  gc_rect =          (0 0 0 0)
  inline =           |During the renovation, the stairways to the balconies are blocked off for safety reasons.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I72D0

trial E4I72D0
  gc_rect =          (0 0 0 0)
  inline =           |During the renovation, the stairway to the balconies are blocked off for safety reasons.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I72D0

trial E102I72D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I72D1

trial E103I72D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I72D1

trial E3I73D0
  gc_rect =          (0 0 0 0)
  inline =           |In the middle of the night, the photographs of the stars are glowing under the soft light.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I73D0

trial E4I73D0
  gc_rect =          (0 0 0 0)
  inline =           |In the middle of the night, the photograph of the stars are glowing under the soft light.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I73D0

trial E102I73D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I73D1

trial E103I73D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I73D1

trial E3I74D0
  gc_rect =          (0 0 0 0)
  inline =           |Without further delay, the maps of the trails are printed for distribution.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I74D0

trial E4I74D0
  gc_rect =          (0 0 0 0)
  inline =           |Without further delay, the map of the trails are printed for distribution.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I74D0

trial E102I74D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I74D1

trial E103I74D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I74D1

trial E3I75D0
  gc_rect =          (0 0 0 0)
  inline =           |Just before sunset, the bridges to the islands are closed to the public.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I75D0

trial E4I75D0
  gc_rect =          (0 0 0 0)
  inline =           |Just before sunset, the bridge to the islands are closed to the public.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I75D0

trial E102I75D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I75D1

trial E103I75D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I75D1

trial E3I76D0
  gc_rect =          (0 0 0 0)
  inline =           |On rainy days, the scents of the flowers are more intense.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I76D0

trial E4I76D0
  gc_rect =          (0 0 0 0)
  inline =           |On rainy days, the scent of the flowers are more intense.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I76D0

trial E102I76D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I76D1

trial E103I76D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I76D1

trial E3I77D0
  gc_rect =          (0 0 0 0)
  inline =           |After the long hike, the views of the mountains are breathtaking, leaving us in awe.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I77D0

trial E4I77D0
  gc_rect =          (0 0 0 0)
  inline =           |After the long hike, the view of the mountains are breathtaking, leaving us in awe.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I77D0

trial E102I77D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I77D1

trial E103I77D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I77D1

trial E3I78D0
  gc_rect =          (0 0 0 0)
  inline =           |Following the lunch break, the curators of the museums are giving a talk to a group of visitors.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I78D0

trial E4I78D0
  gc_rect =          (0 0 0 0)
  inline =           |Following the lunch break, the curator of the museums are giving a talk to a group of visitors.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I78D0

trial E102I78D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I78D1

trial E103I78D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I78D1

trial E3I79D0
  gc_rect =          (0 0 0 0)
  inline =           |Under the microscope, the structures of the cells are revealed in detail.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I79D0

trial E4I79D0
  gc_rect =          (0 0 0 0)
  inline =           |Under the microscope, the structure of the cells are revealed in detail.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I79D0

trial E102I79D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I79D1

trial E103I79D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I79D1

trial E3I80D0
  gc_rect =          (0 0 0 0)
  inline =           |Across the field, the movements of the animals are captivating the children.\n
  max_display_time = 20000
  trial_type =       sentence
end E3I80D0

trial E4I80D0
  gc_rect =          (0 0 0 0)
  inline =           |Across the field, the movement of the animals are captivating the children.\n
  max_display_time = 20000
  trial_type =       sentence
end E4I80D0

trial E102I80D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E102I80D1

trial E103I80D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was there anything wrong with that sentence?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E103I80D1

trial E5I81D0
  gc_rect =          (0 0 0 0)
  inline =           |This is useful for keeping browsing activity private from other users of the same device.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I81D0

trial E100I81D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Is this tool is useful for keeping your data private?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E100I81D1

trial E5I82D0
  gc_rect =          (0 0 0 0)
  inline =           |That's because 90% of the heat energy from climate change goes into the oceans, Willis said.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I82D0

trial E100I82D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What percent of heat energy goes into the ocean?\n\n90                     70\n
  max_display_time = 20000
  trial_type =       question
end E100I82D1

trial E5I83D0
  gc_rect =          (0 0 0 0)
  inline =           |They both end up crashing through the table from the top of the cage.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I83D0

trial E100I83D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What did they crash into?\n\nTABLE                     CHAIR\n
  max_display_time = 20000
  trial_type =       question
end E100I83D1

trial E5I84D0
  gc_rect =          (0 0 0 0)
  inline =           |Perry suffered his injury after being on the end of a flying knee from Luque that laid him out.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I84D0

trial E100I84D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was Perry injured?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E100I84D1

trial E5I85D0
  gc_rect =          (0 0 0 0)
  inline =           |I'm no food critic, so I'm going to have to slip into cliche here and describe the chowder as "succulent."\n
  max_display_time = 20000
  trial_type =       sentence
end E5I85D0

trial E100I85D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Is the author a food critic?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E100I85D1

trial E5I86D0
  gc_rect =          (0 0 0 0)
  inline =           |The checks were cut in federal court this morning, right here in Rockford.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I86D0

trial E100I86D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Which court was the sentence talking about?\n\nFEDERAL                     STATE\n
  max_display_time = 20000
  trial_type =       question
end E100I86D1

trial E5I87D0
  gc_rect =          (0 0 0 0)
  inline =           |We expect someone who wants to work here will have already found us, connected with us, and begun to build a relationship.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I87D0

trial E100I87D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Who are they talking about?\n\nEMPLOYEES                     STUDENTS\n
  max_display_time = 20000
  trial_type =       question
end E100I87D1

trial E5I88D0
  gc_rect =          (0 0 0 0)
  inline =           |Most of us are here to talk about conservative issues first and foremost.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I88D0

trial E100I88D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What kind of issues do they talk about?\n\nCONSERVATIVE                     LIBERAL\n
  max_display_time = 20000
  trial_type =       question
end E100I88D1

trial E5I89D0
  gc_rect =          (0 0 0 0)
  inline =           |Selvaggio's companies never actually provided the services, even though customers were billed for them.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I89D0

trial E100I89D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Were customers properly billed?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E100I89D1

trial E5I90D0
  gc_rect =          (0 0 0 0)
  inline =           |This movie is a slippery slope for viewers who will never research the truth about wolves.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I90D0

trial E100I90D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Does the movie tell the full story about wolves?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E100I90D1

trial E5I91D0
  gc_rect =          (0 0 0 0)
  inline =           |I wake up a lot of days and do things I never expected I'd do as a parent.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I91D0

trial E100I91D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Were all the duties of parenting expected?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E100I91D1

trial E5I92D0
  gc_rect =          (0 0 0 0)
  inline =           |We've gathered some of the coolest art, music, food and theater events happening in the city.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I92D0

trial E100I92D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was theater included in the event?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E100I92D1

trial E5I93D0
  gc_rect =          (0 0 0 0)
  inline =           |It's still early in the season, but they have some tough losses already.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I93D0

trial E100I93D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What part of the season is it?\n\nEARLY                     LATE\n
  max_display_time = 20000
  trial_type =       question
end E100I93D1

trial E5I94D0
  gc_rect =          (0 0 0 0)
  inline =           |Coupled with freezing temps, the fog is making for some slick spots and several crashes were called in prior to 6:30 a.m.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I94D0

trial E100I94D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Does the fog cause problems?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E100I94D1

trial E5I95D0
  gc_rect =          (0 0 0 0)
  inline =           |It's delicious, but then you regret it, because you have heartburn for the rest of the day.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I95D0

trial E100I95D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |How long will you feel heartburn for?\n\nA DAY                     A WEEK\n
  max_display_time = 20000
  trial_type =       question
end E100I95D1

trial E5I96D0
  gc_rect =          (0 0 0 0)
  inline =           |The justices then told the appeals court to take that into consideration in the cross-border case.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I96D0

trial E100I96D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What court is mentioned?\n\nAPPEALS                     DISTRICT\n
  max_display_time = 20000
  trial_type =       question
end E100I96D1

trial E5I97D0
  gc_rect =          (0 0 0 0)
  inline =           |The second class will cover a full Greek meal, which will then be served.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I97D0

trial E101I97D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Which class covers the Greek meal?\n\nFIRST                     SECOND\n
  max_display_time = 20000
  trial_type =       question
end E101I97D1

trial E5I98D0
  gc_rect =          (0 0 0 0)
  inline =           |I don't understand how these folks have apparently never heard of mousepads.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I98D0

trial E101I98D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Have the people heard of mousepads?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E101I98D1

trial E5I99D0
  gc_rect =          (0 0 0 0)
  inline =           |I always tend to imagine what these characters and their voices would sound like.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I99D0

trial E101I99D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Does the author imagine or listen to the characters voices?\n\nLISTEN                     IMAGINE\n
  max_display_time = 20000
  trial_type =       question
end E101I99D1

trial E5I100D0
  gc_rect =          (0 0 0 0)
  inline =           |They also mentioned they didn't know where all these crazy rumors were coming from.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I100D0

trial E101I100D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Do they know where the rumors are coming from?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E101I100D1

trial E5I101D0
  gc_rect =          (0 0 0 0)
  inline =           |Ships traveling through these waters are at the mercy of a continuously harsh climate.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I101D0

trial E101I101D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What are boats vulnerable to?\n\nROT                     CLIMATE\n
  max_display_time = 20000
  trial_type =       question
end E101I101D1

trial E5I102D0
  gc_rect =          (0 0 0 0)
  inline =           |Though some are better than others, I think they all underestimate their audiences.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I102D0

trial E101I102D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Do they over or underestimate their audiences?\n\nOVER                     UNDER\n
  max_display_time = 20000
  trial_type =       question
end E101I102D1

trial E5I103D0
  gc_rect =          (0 0 0 0)
  inline =           |At that point they were playing for pride, and hoping to make the final score more respectable.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I103D0

trial E101I103D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Were they playing to win?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E101I103D1

trial E5I104D0
  gc_rect =          (0 0 0 0)
  inline =           |Jimmy Butler should expect a harsh atmosphere when he faces the Philadelphia 76ers this season.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I104D0

trial E101I104D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What kind of atmosphere should be expected?\n\nWELCOMING                     HARSH\n
  max_display_time = 20000
  trial_type =       question
end E101I104D1

trial E5I105D0
  gc_rect =          (0 0 0 0)
  inline =           |Today, some sites use an unintended loophole to detect when people are browsing in Incognito Mode.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I105D0

trial E101I105D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Is the loophole intended or unintended?\n\nINTENDED                     UNINTENDED\n
  max_display_time = 20000
  trial_type =       question
end E101I105D1

trial E5I106D0
  gc_rect =          (0 0 0 0)
  inline =           |The dragon appears happy when questions are answered, and he becomes hungry when he needs to be fed more answers.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I106D0

trial E101I106D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What is being talked about?\n\nA MONSTER                    A DRAGON\n
  max_display_time = 20000
  trial_type =       question
end E101I106D1

trial E5I107D0
  gc_rect =          (0 0 0 0)
  inline =           |Fit a beet into the front of the spiralizer where spikes hold the vegetable in place.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I107D0

trial E101I107D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What side of the spiralizer does the beet go into?\n\nBACK                     FRONT\n
  max_display_time = 20000
  trial_type =       question
end E101I107D1

trial E5I108D0
  gc_rect =          (0 0 0 0)
  inline =           |But it's a mystery where my mother got the inspiration for this dish.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I108D0

trial E101I108D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Who cooked the dish?\n\nGRANDMOTHER                     MOTHER\n
  max_display_time = 20000
  trial_type =       question
end E101I108D1

trial E5I109D0
  gc_rect =          (0 0 0 0)
  inline =           |The institute's archeologists believe they once covered holes where sacrifices were perhaps buried.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I109D0

trial E101I109D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What was being covered?\n\nCRACKS                     HOLES\n
  max_display_time = 20000
  trial_type =       question
end E101I109D1

trial E5I110D0
  gc_rect =          (0 0 0 0)
  inline =           |That's part of being on a team where you're still trying to figure things out.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I110D0

trial E101I110D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Was the event team based?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E101I110D1

trial E5I111D0
  gc_rect =          (0 0 0 0)
  inline =           |At that point, the partial closure will have lasted 18 days.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I111D0

trial E101I111D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |The closure lasted how many days?\n\n8                     18\n
  max_display_time = 20000
  trial_type =       question
end E101I111D1

trial E5I112D0
  gc_rect =          (0 0 0 0)
  inline =           |That session will occur 11 a.m. at the White House, according to a congressional official.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I112D0

trial E101I112D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |The session will occur when?\n\n3                     11\n
  max_display_time = 20000
  trial_type =       question
end E101I112D1

trial E5I113D0
  gc_rect =          (0 0 0 0)
  inline =           |Sometimes one of the people will bring some cleaning help in for her specific needs, but that is not for the common areas.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I113D0

trial E101I113D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Do people ever bring help?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E101I113D1

trial E5I114D0
  gc_rect =          (0 0 0 0)
  inline =           |This event will feature four title matches and one additional bout.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I114D0

trial E101I114D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |The event will have how many title matches?\n\n2                     4\n
  max_display_time = 20000
  trial_type =       question
end E101I114D1

trial E5I115D0
  gc_rect =          (0 0 0 0)
  inline =           |You can make it as a lasagna with pasta sheets and plenty of cheese or you can make your own ravioli.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I115D0

trial E101I115D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What kind of pasta was mentioned?\n\nPENNE                     LASAGNA\n
  max_display_time = 20000
  trial_type =       question
end E101I115D1

trial E5I116D0
  gc_rect =          (0 0 0 0)
  inline =           |I brought everything I could with me, including my current reading projects, so I could go to my favorite cafe.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I116D0

trial E101I116D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What the person bring?\n\nMUSIC                     READING\n
  max_display_time = 20000
  trial_type =       question
end E101I116D1

trial E5I117D0
  gc_rect =          (0 0 0 0)
  inline =           |But before you check that one out, stretch your mind a bit with some of these sci-fi brain busters.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I117D0

trial E101I117D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What genre are the brain busters?\n\nMYSTERY                     SCI-FI\n
  max_display_time = 20000
  trial_type =       question
end E101I117D1

trial E5I118D0
  gc_rect =          (0 0 0 0)
  inline =           |In this view, promoting body acceptance would only undermine behavior change and encourage obesity.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I118D0

trial E101I118D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What is being promoted?\n\nEXERCISE                    BODY ACCEPTANCE\n
  max_display_time = 20000
  trial_type =       question
end E101I118D1

trial E5I119D0
  gc_rect =          (0 0 0 0)
  inline =           |Zanette says there is no guarantee when, or even if, the designation will be approved.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I119D0

trial E101I119D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |How certain is it that it will be approved?\n\nCERTAIN                     UNCERTAIN\n
  max_display_time = 20000
  trial_type =       question
end E101I119D1

trial E5I120D0
  gc_rect =          (0 0 0 0)
  inline =           |Personally, little of how others lead their lives has affected my life and the relationship I have with my wife and kids.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I120D0

trial E101I120D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Is the speaker married?\n\nNO                     YES\n       
  max_display_time = 20000
  trial_type =       question
end E101I120D1

trial E5I121D0
  gc_rect =          (0 0 0 0)
  inline =           |But, to be honest, I was interacting with folks that just did not adequately communicate in English.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I121D0

trial E101I121D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Did the speaker find communicating easy?\n\nYES                     NO\n              
  max_display_time = 20000
  trial_type =       question
end E101I121D1

trial E5I122D0
  gc_rect =          (0 0 0 0)
  inline =           |I love rooms decorated with touches of Americana, or just her colors.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I122D0

trial E101I122D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What design style are they fond of?\n\nART DECO                     AMERICANA\n
  max_display_time = 20000
  trial_type =       question
end E101I122D1

trial E5I123D0
  gc_rect =          (0 0 0 0)
  inline =           |Originally, I thought I would go on a second date, but there was no real connection.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I123D0

trial E101I123D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |How did the first date go?\n\nWELL                     POORLY\n
  max_display_time = 20000
  trial_type =       question
end E101I123D1

trial E5I124D0
  gc_rect =          (0 0 0 0)
  inline =           |Think how much happier the world would be if we all added this plugin before his next album comes out!\n
  max_display_time = 20000
  trial_type =       sentence
end E5I124D0

trial E101I124D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |When should people get?\n\nAN APP                     A PLUGIN\n
  max_display_time = 20000
  trial_type =       question
end E101I124D1

trial E5I125D0
  gc_rect =          (0 0 0 0)
  inline =           |She's as smart as they come and she's so with it.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I125D0

trial E101I125D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What word best describes the girl?\n\nFOOLISH                     INTELLIGENT\n
  max_display_time = 20000
  trial_type =       question
end E101I125D1

trial E5I126D0
  gc_rect =          (0 0 0 0)
  inline =           |Those who know better know that all good things come to an end.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I126D0

trial E101I126D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Do good things last forever?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E101I126D1

trial E5I127D0
  gc_rect =          (0 0 0 0)
  inline =           |What happened here may well be a sign of things to come if the drought continues.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I127D0

trial E101I127D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What type of natural disaster is occurring?\n\nHURRICANE                     DROUGHT\n
  max_display_time = 20000
  trial_type =       question
end E101I127D1

trial E5I128D0
  gc_rect =          (0 0 0 0)
  inline =           |Some of his ideas sound like the rhetoric of someone who doesn't plan to be around when the chickens come home to roost.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I128D0

trial E101I128D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Is the speaker discussing a reliable person?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E101I128D1

trial E5I129D0
  gc_rect =          (0 0 0 0)
  inline =           |It's about a friendship between a little girl and her teddy bear.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I129D0

trial E101I129D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Who owns the teddy bear?\n\nAN ADULT                     A CHILD\n
  max_display_time = 20000
  trial_type =       question
end E101I129D1

trial E5I130D0
  gc_rect =          (0 0 0 0)
  inline =           |Polly and Elliott Mayfield last year welcomed a baby girl into their family.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I130D0

trial E101I130D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |When was the baby born?\n\nLAST WEEK                     LAST YEAR\n
  max_display_time = 20000
  trial_type =       question
end E101I130D1

trial E5I131D0
  gc_rect =          (0 0 0 0)
  inline =           |Officials responded to Norwich for the report of an 11-year-old girl in cardiac arrest.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I131D0

trial E101I131D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Where did this take place?\n\nYORK                     NORWICH\n
  max_display_time = 20000
  trial_type =       question
end E101I131D1

trial E5I132D0
  gc_rect =          (0 0 0 0)
  inline =           |It feels really good to be a part of the first Surf League championship.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I132D0

trial E101I132D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Is the speaker excited to compete?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E101I132D1

trial E5I133D0
  gc_rect =          (0 0 0 0)
  inline =           |The adage of "if it seems too good to be true, it is," holds true at the shows.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I133D0

trial E101I133D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Is everything as it seems?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E101I133D1

trial E5I134D0
  gc_rect =          (0 0 0 0)
  inline =           |Wade has had a pretty good season featuring 13.8 points per game and a sweet little goodbye moment with his old pal.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I134D0

trial E101I134D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Who did Wade say goodbye to?\n\nHIS PARENT                     HIS FRIEND\n
  max_display_time = 20000
  trial_type =       question
end E101I134D1

trial E5I135D0
  gc_rect =          (0 0 0 0)
  inline =           |So take the time to get to know your engineering team before you're working on the next big project together.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I135D0

trial E101I135D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What type of team was put together?\n\nCHEMISTRY                     ENGINEERING\n
  max_display_time = 20000
  trial_type =       question
end E101I135D1

trial E5I136D0
  gc_rect =          (0 0 0 0)
  inline =           |It's been months and I don't even know where to begin.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I136D0

trial E101I136D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |How does the speaker feel?\n\nCONFIDENT                     OVERWHELMED\n
  max_display_time = 20000
  trial_type =       question
end E101I136D1

trial E5I137D0
  gc_rect =          (0 0 0 0)
  inline =           |Most officers that I know are gun guys anyway, but there are those who are not.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I137D0

trial E101I137D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Are all officers into guns?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E101I137D1

trial E5I138D0
  gc_rect =          (0 0 0 0)
  inline =           |The NBA's youngest stars also know they can work off bad food a little more easily.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I138D0

trial E101I138D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Who is being talked about?\n\nOLDER PLAYERS                    YOUNGER PLAYERS\n
  max_display_time = 20000
  trial_type =       question
end E101I138D1

trial E5I139D0
  gc_rect =          (0 0 0 0)
  inline =           |They're all there, in a neat little helpfully compiled list.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I139D0

trial E101I139D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Is the list organized?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E101I139D1

trial E5I140D0
  gc_rect =          (0 0 0 0)
  inline =           |So what finally happened was I got a deal for very little money to develop Star Wars.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I140D0

trial E101I140D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What kind of funding was given for the project?\n\nGENEROUS                     SCARCE\n
  max_display_time = 20000
  trial_type =       question
end E101I140D1

trial E5I141D0
  gc_rect =          (0 0 0 0)
  inline =           |They fell in love and were married six months later.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I141D0

trial E101I141D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |How long did it take for them to get married?\n\n4 MONTHS                     6 MONTHS\n
  max_display_time = 20000
  trial_type =       question
end E101I141D1

trial E5I142D0
  gc_rect =          (0 0 0 0)
  inline =           |I sure would love to cycle to work (and have in the past) but it is not currently feasible.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I142D0

trial E101I142D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What exercise is enjoyed?\n\nRUNNING                     CYCLING\n
  max_display_time = 20000
  trial_type =       question
end E101I142D1

trial E5I143D0
  gc_rect =          (0 0 0 0)
  inline =           |Bring your friends and family, and tell everyone you know how much you love those places.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I143D0

trial E101I143D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |How should these places be enjoyed?\n\nALONE                     WITH OTHERS\n
  max_display_time = 20000
  trial_type =       question
end E101I143D1

trial E5I144D0
  gc_rect =          (0 0 0 0)
  inline =           |I'm a good cook and I know how to make all kinds of soups.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I144D0

trial E100I144D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What kind of food do they make?\n\nSOUP                     SALAD\n
  max_display_time = 20000
  trial_type =       question
end E100I144D1

trial E5I145D0
  gc_rect =          (0 0 0 0)
  inline =           |These artisans know how to make affordable jewelry look like a million bucks.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I145D0

trial E100I145D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |How much does the jewelry cost?\n\nA LITTLE                     A LOT\n
  max_display_time = 20000
  trial_type =       question
end E100I145D1

trial E5I146D0
  gc_rect =          (0 0 0 0)
  inline =           |Here are a few players who will certainly be drafted but did not quite make the cut.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I146D0

trial E100I146D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Will they be drafted?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E100I146D1

trial E5I147D0
  gc_rect =          (0 0 0 0)
  inline =           |She says the very qualities that make us successful are the same ones that can take us down.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I147D0

trial E100I147D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Do good qualities produce only good outcomes?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E100I147D1

trial E5I148D0
  gc_rect =          (0 0 0 0)
  inline =           |And now I have a career where I'm making enough money to live.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I148D0

trial E100I148D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Does the speaker make enough money?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E100I148D1

trial E5I149D0
  gc_rect =          (0 0 0 0)
  inline =           |Make sure that the account you use to enter the contest includes your real name and a contact email.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I149D0

trial E100I149D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Can the account use a nickname?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E100I149D1

trial E5I150D0
  gc_rect =          (0 0 0 0)
  inline =           |The technique gets its name because, like snowshoes, it distributes the heavy load evenly across a wide area.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I150D0

trial E100I150D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What is mentioned in this sentence?\n\nSNOWSHOES                     SKIS\n
  max_display_time = 20000
  trial_type =       question
end E100I150D1

trial E5I151D0
  gc_rect =          (0 0 0 0)
  inline =           |What ensued Friday night was a mixture of boos, cheers and general awkwardness.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I151D0

trial E100I151D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What was the reaction to the events of Friday?\n\nMIXED                     POSITIVE\n
  max_display_time = 20000
  trial_type =       question
end E100I151D1

trial E5I152D0
  gc_rect =          (0 0 0 0)
  inline =           |That being said I have heard from a lot of people that they want to do it anyways.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I152D0

trial E100I152D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Are people afraid of the consequences?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E100I152D1

trial E5I153D0
  gc_rect =          (0 0 0 0)
  inline =           |You enjoy attracting influential people who bring advantage and romantic intrigue.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I153D0

trial E100I153D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What kind of people are mentioned?\n\nINFLUENTIAL                    CRIMINAL\n
  max_display_time = 20000
  trial_type =       question
end E100I153D1

trial E5I154D0
  gc_rect =          (0 0 0 0)
  inline =           |I don't think that system is perfect but it was better than it is now.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I154D0

trial E100I154D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Has the system improved?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E100I154D1

trial E5I155D0
  gc_rect =          (0 0 0 0)
  inline =           |We want to hear what you think about this article.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I155D0

trial E100I155D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Does the speaker like feedback?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E100I155D1

trial E5I156D0
  gc_rect =          (0 0 0 0)
  inline =           |Get some rest and don't even think about this place for the next two weeks.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I156D0

trial E100I156D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |How many weeks are they resting for?\n\nTWO                     THREE\n
  max_display_time = 20000
  trial_type =       question
end E100I156D1

trial E5I157D0
  gc_rect =          (0 0 0 0)
  inline =           |For the first time ever, the awards program will livestream globally.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I157D0

trial E100I157D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Where is the livestream occurring?\n\nGLOBALLY                     NATIONALLY\n
  max_display_time = 20000
  trial_type =       question
end E100I157D1

trial E5I158D0
  gc_rect =          (0 0 0 0)
  inline =           |Now comes the good part boys and girls, the part the Main Stream Media doesn't want to talk about.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I158D0

trial E100I158D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Which best describes the media?\n\nSECRETIVE                     HONEST\n
  max_display_time = 20000
  trial_type =       question
end E100I158D1

trial E5I159D0
  gc_rect =          (0 0 0 0)
  inline =           |What kind of job would you get at your age, with your skill set if you got fired from the Chicago Police Department?\n
  max_display_time = 20000
  trial_type =       sentence
end E5I159D0

trial E100I159D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Could the subject easily find a new job?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E100I159D1

trial E5I160D0
  gc_rect =          (0 0 0 0)
  inline =           |Each posted position has a detailed job description so students know what their duties would be if selected.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I160D0

trial E100I160D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Will the students know what their duties are?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E100I160D1

trial E5I161D0
  gc_rect =          (0 0 0 0)
  inline =           |The sales tax increase is tied to transportation and would fund more than a dozen major transit projects.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I161D0

trial E100I161D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Which tax is tied to transportation?\n\nSALES TAX                     INCOME TAX\n
  max_display_time = 20000
  trial_type =       question
end E100I161D1

trial E5I162D0
  gc_rect =          (0 0 0 0)
  inline =           |All three of these elements come together when Grunkle Stan throws a fair in town, full of scarily cheap rides.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I162D0

trial E100I162D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What did Grunkle Stan throw?\n\nFAIR                     CARNIVAL\n
  max_display_time = 20000
  trial_type =       question
end E100I162D1

trial E5I163D0
  gc_rect =          (0 0 0 0)
  inline =           |It was a decision that would later come to haunt the Japanese company.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I163D0

trial E100I163D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What were the consequences of the decision?\n\nBAD                     GOOD\n
  max_display_time = 20000
  trial_type =       question
end E100I163D1

trial E5I164D0
  gc_rect =          (0 0 0 0)
  inline =           |I think I may be part dolphin because I only ever come up to breathe.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I164D0

trial E100I164D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Does the author like to swim?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E100I164D1

trial E5I165D0
  gc_rect =          (0 0 0 0)
  inline =           |I have a maid come in once a month to clean my apartment.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I165D0

trial E100I165D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |How many times a month does the maid come?\n\nONCE                     THREE\n
  max_display_time = 20000
  trial_type =       question
end E100I165D1

trial E5I166D0
  gc_rect =          (0 0 0 0)
  inline =           |I'm sure there is a girl out there that will appreciate you.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I166D0

trial E100I166D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Is the subject in a relationship right now?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E100I166D1

trial E5I167D0
  gc_rect =          (0 0 0 0)
  inline =           |I'm the girl who just thinks up something as I'm walking into a tattoo parlor.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I167D0

trial E100I167D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What kind of person is the girl?\n\nSPONTANEOUS                     ANXIOUS\n
  max_display_time = 20000
  trial_type =       question
end E100I167D1

trial E5I168D0
  gc_rect =          (0 0 0 0)
  inline =           |I couldn't believe that Amanda let the girl take her phone and never did anything about it.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I168D0

trial E100I168D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Whose phone did the girl take?\n\nAMANDA                    ALEX\n
  max_display_time = 20000
  trial_type =       question
end E100I168D1

trial E5I169D0
  gc_rect =          (0 0 0 0)
  inline =           |Last year, the life-insurance company surveyed more than 1,000 people about the most memorable love letters ever penned.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I169D0

trial E101I169D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |How many people did they survey?\n\n100                     1,000\n
  max_display_time = 20000
  trial_type =       question
end E101I169D1

trial E5I170D0
  gc_rect =          (0 0 0 0)
  inline =           |The pickles definitely make a statement.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I170D0

trial E101I170D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What makes a statement?\n\nPICKLES                     NUTS\n
  max_display_time = 20000
  trial_type =       question
end E101I170D1

trial E5I171D0
  gc_rect =          (0 0 0 0)
  inline =           |Tesla has only about $5 billion in cash, and it has lost money every quarter save three in its decade-and-a-half existence.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I171D0

trial E101I171D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Has Tesla made money consistently?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E101I171D1

trial E5I172D0
  gc_rect =          (0 0 0 0)
  inline =           |Precipitation may return Sunday night with rain, snow and freezing rain before 3 a.m.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I172D0

trial E101I172D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |When will the precipitation possibly return?\n\nNIGHT                     MORNING\n
  max_display_time = 20000
  trial_type =       question
end E101I172D1

trial E5I173D0
  gc_rect =          (0 0 0 0)
  inline =           |In fandom, there are some people who express their love through hate.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I173D0

trial E101I173D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Do people express their feelings straightforwardly?\n\nNO                    YES\n
  max_display_time = 20000
  trial_type =       question
end E101I173D1

trial E5I174D0
  gc_rect =          (0 0 0 0)
  inline =           |We don't think about tapping into what makes us human.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I174D0

trial E101I174D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Do we acknowledge our human nature?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E101I174D1

trial E5I175D0
  gc_rect =          (0 0 0 0)
  inline =           |I just think something needs to change.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I175D0

trial E101I175D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Is everything fine?\n\nNO                     YES\n
  max_display_time = 20000
  trial_type =       question
end E101I175D1

trial E5I176D0
  gc_rect =          (0 0 0 0)
  inline =           |Either way I think he's a prime candidate for a breakout season next year.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I176D0

trial E101I176D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |When will the breakout be?\n\nNEXT YEAR                     THIS YEAR\n
  max_display_time = 20000
  trial_type =       question
end E101I176D1

trial E5I177D0
  gc_rect =          (0 0 0 0)
  inline =           |He says it's time for him to hang up his mask and retire.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I177D0

trial E101I177D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Is it time for him to retire?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E101I177D1

trial E5I178D0
  gc_rect =          (0 0 0 0)
  inline =           |This series of articles will be talking about the fundamentals of deck construction.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I178D0

trial E101I178D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What type of construction?\n\nDECK                     HOUSE\n
  max_display_time = 20000
  trial_type =       question
end E101I178D1

trial E5I179D0
  gc_rect =          (0 0 0 0)
  inline =           |Politicians should be thinking about their futures, because that future might just depend on how they vote.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I179D0

trial E101I179D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What should politicians be thinking about?\n\nFUTURE                     PAST\n
  max_display_time = 20000
  trial_type =       question
end E101I179D1

trial E5I180D0
  gc_rect =          (0 0 0 0)
  inline =           | and CIA were both in the know about the chances of this happening.\n
  max_display_time = 20000
  trial_type =       sentence
end E5I180D0

trial E101I180D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Were the FBI and CIA in the know?\n\nYES                     NO\n
  max_display_time = 20000
  trial_type =       question
end E101I180D1

trial E104I900D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Who did the Red Sox beat?\n\nTHE YANKEES           THE PHILLIES\n
  max_display_time = 1500000
  trial_type =       question
end E104I900D1

trial E104I905D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What kind of attention is important?\n\nAUDITORY            VISUAL\n
  max_display_time = 1500000
  trial_type =       question
end E104I905D1

trial E104I906D1
  button =           rightTrigger
  gc_rect =          (0 0 0 0)
  inline =           |Who is one of the greatest masters?\n\nPICASSO            REMBRANDT\n
  max_display_time = 1500000
  trial_type =       question
end E104I906D1

trial E104I907D1
  button =           leftTrigger
  gc_rect =          (0 0 0 0)
  inline =           |What showed up on campus?\n\nA MOOSE           A DEER\n
  max_display_time = 1500000
  trial_type =       question
end E104I907D1

sequence SP99I900
  P99I900D0
  E104I900D1
end SP99I900

sequence SP99I905
  P99I905D0
  E104I905D1
end SP99I905

sequence SP99I906
  P99I906D0
  E104I906D1
end SP99I906

sequence SP99I907
  P99I907D0
  E104I907D1
end SP99I907

sequence SE1I1
  E1I1D0
  E102I1D1
end SE1I1

sequence SE2I1
  E2I1D0
  E103I1D1
end SE2I1

sequence SE1I2
  E1I2D0
  E102I2D1
end SE1I2

sequence SE2I2
  E2I2D0
  E103I2D1
end SE2I2

sequence SE1I3
  E1I3D0
  E102I3D1
end SE1I3

sequence SE2I3
  E2I3D0
  E103I3D1
end SE2I3

sequence SE1I4
  E1I4D0
  E102I4D1
end SE1I4

sequence SE2I4
  E2I4D0
  E103I4D1
end SE2I4

sequence SE1I5
  E1I5D0
  E102I5D1
end SE1I5

sequence SE2I5
  E2I5D0
  E103I5D1
end SE2I5

sequence SE1I6
  E1I6D0
  E102I6D1
end SE1I6

sequence SE2I6
  E2I6D0
  E103I6D1
end SE2I6

sequence SE1I7
  E1I7D0
  E102I7D1
end SE1I7

sequence SE2I7
  E2I7D0
  E103I7D1
end SE2I7

sequence SE1I8
  E1I8D0
  E102I8D1
end SE1I8

sequence SE2I8
  E2I8D0
  E103I8D1
end SE2I8

sequence SE1I9
  E1I9D0
  E102I9D1
end SE1I9

sequence SE2I9
  E2I9D0
  E103I9D1
end SE2I9

sequence SE1I10
  E1I10D0
  E102I10D1
end SE1I10

sequence SE2I10
  E2I10D0
  E103I10D1
end SE2I10

sequence SE1I11
  E1I11D0
  E102I11D1
end SE1I11

sequence SE2I11
  E2I11D0
  E103I11D1
end SE2I11

sequence SE1I12
  E1I12D0
  E102I12D1
end SE1I12

sequence SE2I12
  E2I12D0
  E103I12D1
end SE2I12

sequence SE1I13
  E1I13D0
  E102I13D1
end SE1I13

sequence SE2I13
  E2I13D0
  E103I13D1
end SE2I13

sequence SE1I14
  E1I14D0
  E102I14D1
end SE1I14

sequence SE2I14
  E2I14D0
  E103I14D1
end SE2I14

sequence SE1I15
  E1I15D0
  E102I15D1
end SE1I15

sequence SE2I15
  E2I15D0
  E103I15D1
end SE2I15

sequence SE1I16
  E1I16D0
  E102I16D1
end SE1I16

sequence SE2I16
  E2I16D0
  E103I16D1
end SE2I16

sequence SE1I17
  E1I17D0
  E102I17D1
end SE1I17

sequence SE2I17
  E2I17D0
  E103I17D1
end SE2I17

sequence SE1I18
  E1I18D0
  E102I18D1
end SE1I18

sequence SE2I18
  E2I18D0
  E103I18D1
end SE2I18

sequence SE1I19
  E1I19D0
  E102I19D1
end SE1I19

sequence SE2I19
  E2I19D0
  E103I19D1
end SE2I19

sequence SE1I20
  E1I20D0
  E102I20D1
end SE1I20

sequence SE2I20
  E2I20D0
  E103I20D1
end SE2I20

sequence SE1I21
  E1I21D0
  E102I21D1
end SE1I21

sequence SE2I21
  E2I21D0
  E103I21D1
end SE2I21

sequence SE1I22
  E1I22D0
  E102I22D1
end SE1I22

sequence SE2I22
  E2I22D0
  E103I22D1
end SE2I22

sequence SE1I23
  E1I23D0
  E102I23D1
end SE1I23

sequence SE2I23
  E2I23D0
  E103I23D1
end SE2I23

sequence SE1I24
  E1I24D0
  E102I24D1
end SE1I24

sequence SE2I24
  E2I24D0
  E103I24D1
end SE2I24

sequence SE1I25
  E1I25D0
  E102I25D1
end SE1I25

sequence SE2I25
  E2I25D0
  E103I25D1
end SE2I25

sequence SE1I26
  E1I26D0
  E102I26D1
end SE1I26

sequence SE2I26
  E2I26D0
  E103I26D1
end SE2I26

sequence SE1I27
  E1I27D0
  E102I27D1
end SE1I27

sequence SE2I27
  E2I27D0
  E103I27D1
end SE2I27

sequence SE1I28
  E1I28D0
  E102I28D1
end SE1I28

sequence SE2I28
  E2I28D0
  E103I28D1
end SE2I28

sequence SE1I29
  E1I29D0
  E102I29D1
end SE1I29

sequence SE2I29
  E2I29D0
  E103I29D1
end SE2I29

sequence SE1I30
  E1I30D0
  E102I30D1
end SE1I30

sequence SE2I30
  E2I30D0
  E103I30D1
end SE2I30

sequence SE1I31
  E1I31D0
  E102I31D1
end SE1I31

sequence SE2I31
  E2I31D0
  E103I31D1
end SE2I31

sequence SE1I32
  E1I32D0
  E102I32D1
end SE1I32

sequence SE2I32
  E2I32D0
  E103I32D1
end SE2I32

sequence SE1I33
  E1I33D0
  E102I33D1
end SE1I33

sequence SE2I33
  E2I33D0
  E103I33D1
end SE2I33

sequence SE1I34
  E1I34D0
  E102I34D1
end SE1I34

sequence SE2I34
  E2I34D0
  E103I34D1
end SE2I34

sequence SE1I35
  E1I35D0
  E102I35D1
end SE1I35

sequence SE2I35
  E2I35D0
  E103I35D1
end SE2I35

sequence SE1I36
  E1I36D0
  E102I36D1
end SE1I36

sequence SE2I36
  E2I36D0
  E103I36D1
end SE2I36

sequence SE1I37
  E1I37D0
  E102I37D1
end SE1I37

sequence SE2I37
  E2I37D0
  E103I37D1
end SE2I37

sequence SE1I38
  E1I38D0
  E102I38D1
end SE1I38

sequence SE2I38
  E2I38D0
  E103I38D1
end SE2I38

sequence SE1I39
  E1I39D0
  E102I39D1
end SE1I39

sequence SE2I39
  E2I39D0
  E103I39D1
end SE2I39

sequence SE1I40
  E1I40D0
  E102I40D1
end SE1I40

sequence SE2I40
  E2I40D0
  E103I40D1
end SE2I40

sequence SE3I41
  E3I41D0
  E102I41D1
end SE3I41

sequence SE4I41
  E4I41D0
  E103I41D1
end SE4I41

sequence SE3I42
  E3I42D0
  E102I42D1
end SE3I42

sequence SE4I42
  E4I42D0
  E103I42D1
end SE4I42

sequence SE3I43
  E3I43D0
  E102I43D1
end SE3I43

sequence SE4I43
  E4I43D0
  E103I43D1
end SE4I43

sequence SE3I44
  E3I44D0
  E102I44D1
end SE3I44

sequence SE4I44
  E4I44D0
  E103I44D1
end SE4I44

sequence SE3I45
  E3I45D0
  E102I45D1
end SE3I45

sequence SE4I45
  E4I45D0
  E103I45D1
end SE4I45

sequence SE3I46
  E3I46D0
  E102I46D1
end SE3I46

sequence SE4I46
  E4I46D0
  E103I46D1
end SE4I46

sequence SE3I47
  E3I47D0
  E102I47D1
end SE3I47

sequence SE4I47
  E4I47D0
  E103I47D1
end SE4I47

sequence SE3I48
  E3I48D0
  E102I48D1
end SE3I48

sequence SE4I48
  E4I48D0
  E103I48D1
end SE4I48

sequence SE3I49
  E3I49D0
  E102I49D1
end SE3I49

sequence SE4I49
  E4I49D0
  E103I49D1
end SE4I49

sequence SE3I50
  E3I50D0
  E102I50D1
end SE3I50

sequence SE4I50
  E4I50D0
  E103I50D1
end SE4I50

sequence SE3I51
  E3I51D0
  E102I51D1
end SE3I51

sequence SE4I51
  E4I51D0
  E103I51D1
end SE4I51

sequence SE3I52
  E3I52D0
  E102I52D1
end SE3I52

sequence SE4I52
  E4I52D0
  E103I52D1
end SE4I52

sequence SE3I53
  E3I53D0
  E102I53D1
end SE3I53

sequence SE4I53
  E4I53D0
  E103I53D1
end SE4I53

sequence SE3I54
  E3I54D0
  E102I54D1
end SE3I54

sequence SE4I54
  E4I54D0
  E103I54D1
end SE4I54

sequence SE3I55
  E3I55D0
  E102I55D1
end SE3I55

sequence SE4I55
  E4I55D0
  E103I55D1
end SE4I55

sequence SE3I56
  E3I56D0
  E102I56D1
end SE3I56

sequence SE4I56
  E4I56D0
  E103I56D1
end SE4I56

sequence SE3I57
  E3I57D0
  E102I57D1
end SE3I57

sequence SE4I57
  E4I57D0
  E103I57D1
end SE4I57

sequence SE3I58
  E3I58D0
  E102I58D1
end SE3I58

sequence SE4I58
  E4I58D0
  E103I58D1
end SE4I58

sequence SE3I59
  E3I59D0
  E102I59D1
end SE3I59

sequence SE4I59
  E4I59D0
  E103I59D1
end SE4I59

sequence SE3I60
  E3I60D0
  E102I60D1
end SE3I60

sequence SE4I60
  E4I60D0
  E103I60D1
end SE4I60

sequence SE3I61
  E3I61D0
  E102I61D1
end SE3I61

sequence SE4I61
  E4I61D0
  E103I61D1
end SE4I61

sequence SE3I62
  E3I62D0
  E102I62D1
end SE3I62

sequence SE4I62
  E4I62D0
  E103I62D1
end SE4I62

sequence SE3I63
  E3I63D0
  E102I63D1
end SE3I63

sequence SE4I63
  E4I63D0
  E103I63D1
end SE4I63

sequence SE3I64
  E3I64D0
  E102I64D1
end SE3I64

sequence SE4I64
  E4I64D0
  E103I64D1
end SE4I64

sequence SE3I65
  E3I65D0
  E102I65D1
end SE3I65

sequence SE4I65
  E4I65D0
  E103I65D1
end SE4I65

sequence SE3I66
  E3I66D0
  E102I66D1
end SE3I66

sequence SE4I66
  E4I66D0
  E103I66D1
end SE4I66

sequence SE3I67
  E3I67D0
  E102I67D1
end SE3I67

sequence SE4I67
  E4I67D0
  E103I67D1
end SE4I67

sequence SE3I68
  E3I68D0
  E102I68D1
end SE3I68

sequence SE4I68
  E4I68D0
  E103I68D1
end SE4I68

sequence SE3I69
  E3I69D0
  E102I69D1
end SE3I69

sequence SE4I69
  E4I69D0
  E103I69D1
end SE4I69

sequence SE3I70
  E3I70D0
  E102I70D1
end SE3I70

sequence SE4I70
  E4I70D0
  E103I70D1
end SE4I70

sequence SE3I71
  E3I71D0
  E102I71D1
end SE3I71

sequence SE4I71
  E4I71D0
  E103I71D1
end SE4I71

sequence SE3I72
  E3I72D0
  E102I72D1
end SE3I72

sequence SE4I72
  E4I72D0
  E103I72D1
end SE4I72

sequence SE3I73
  E3I73D0
  E102I73D1
end SE3I73

sequence SE4I73
  E4I73D0
  E103I73D1
end SE4I73

sequence SE3I74
  E3I74D0
  E102I74D1
end SE3I74

sequence SE4I74
  E4I74D0
  E103I74D1
end SE4I74

sequence SE3I75
  E3I75D0
  E102I75D1
end SE3I75

sequence SE4I75
  E4I75D0
  E103I75D1
end SE4I75

sequence SE3I76
  E3I76D0
  E102I76D1
end SE3I76

sequence SE4I76
  E4I76D0
  E103I76D1
end SE4I76

sequence SE3I77
  E3I77D0
  E102I77D1
end SE3I77

sequence SE4I77
  E4I77D0
  E103I77D1
end SE4I77

sequence SE3I78
  E3I78D0
  E102I78D1
end SE3I78

sequence SE4I78
  E4I78D0
  E103I78D1
end SE4I78

sequence SE3I79
  E3I79D0
  E102I79D1
end SE3I79

sequence SE4I79
  E4I79D0
  E103I79D1
end SE4I79

sequence SE3I80
  E3I80D0
  E102I80D1
end SE3I80

sequence SE4I80
  E4I80D0
  E103I80D1
end SE4I80

sequence SE5I81
  E5I81D0
  E100I81D1
end SE5I81

sequence SE5I82
  E5I82D0
  E100I82D1
end SE5I82

sequence SE5I83
  E5I83D0
  E100I83D1
end SE5I83

sequence SE5I84
  E5I84D0
  E100I84D1
end SE5I84

sequence SE5I85
  E5I85D0
  E100I85D1
end SE5I85

sequence SE5I86
  E5I86D0
  E100I86D1
end SE5I86

sequence SE5I87
  E5I87D0
  E100I87D1
end SE5I87

sequence SE5I88
  E5I88D0
  E100I88D1
end SE5I88

sequence SE5I89
  E5I89D0
  E100I89D1
end SE5I89

sequence SE5I90
  E5I90D0
  E100I90D1
end SE5I90

sequence SE5I91
  E5I91D0
  E100I91D1
end SE5I91

sequence SE5I92
  E5I92D0
  E100I92D1
end SE5I92

sequence SE5I93
  E5I93D0
  E100I93D1
end SE5I93

sequence SE5I94
  E5I94D0
  E100I94D1
end SE5I94

sequence SE5I95
  E5I95D0
  E100I95D1
end SE5I95

sequence SE5I96
  E5I96D0
  E100I96D1
end SE5I96

sequence SE5I97
  E5I97D0
  E101I97D1
end SE5I97

sequence SE5I98
  E5I98D0
  E101I98D1
end SE5I98

sequence SE5I99
  E5I99D0
  E101I99D1
end SE5I99

sequence SE5I100
  E5I100D0
  E101I100D1
end SE5I100

sequence SE5I101
  E5I101D0
  E101I101D1
end SE5I101

sequence SE5I102
  E5I102D0
  E101I102D1
end SE5I102

sequence SE5I103
  E5I103D0
  E101I103D1
end SE5I103

sequence SE5I104
  E5I104D0
  E101I104D1
end SE5I104

sequence SE5I105
  E5I105D0
  E101I105D1
end SE5I105

sequence SE5I106
  E5I106D0
  E101I106D1
end SE5I106

sequence SE5I107
  E5I107D0
  E101I107D1
end SE5I107

sequence SE5I108
  E5I108D0
  E101I108D1
end SE5I108

sequence SE5I109
  E5I109D0
  E101I109D1
end SE5I109

sequence SE5I110
  E5I110D0
  E101I110D1
end SE5I110

sequence SE5I111
  E5I111D0
  E101I111D1
end SE5I111

sequence SE5I112
  E5I112D0
  E101I112D1
end SE5I112

sequence SE5I113
  E5I113D0
  E101I113D1
end SE5I113

sequence SE5I114
  E5I114D0
  E101I114D1
end SE5I114

sequence SE5I115
  E5I115D0
  E101I115D1
end SE5I115

sequence SE5I116
  E5I116D0
  E101I116D1
end SE5I116

sequence SE5I117
  E5I117D0
  E101I117D1
end SE5I117

sequence SE5I118
  E5I118D0
  E101I118D1
end SE5I118

sequence SE5I119
  E5I119D0
  E101I119D1
end SE5I119

sequence SE5I120
  E5I120D0
  E101I120D1
end SE5I120

sequence SE5I121
  E5I121D0
  E101I121D1
end SE5I121

sequence SE5I122
  E5I122D0
  E101I122D1
end SE5I122

sequence SE5I123
  E5I123D0
  E101I123D1
end SE5I123

sequence SE5I124
  E5I124D0
  E101I124D1
end SE5I124

sequence SE5I125
  E5I125D0
  E101I125D1
end SE5I125

sequence SE5I126
  E5I126D0
  E101I126D1
end SE5I126

sequence SE5I127
  E5I127D0
  E101I127D1
end SE5I127

sequence SE5I128
  E5I128D0
  E101I128D1
end SE5I128

sequence SE5I129
  E5I129D0
  E101I129D1
end SE5I129

sequence SE5I130
  E5I130D0
  E101I130D1
end SE5I130

sequence SE5I131
  E5I131D0
  E101I131D1
end SE5I131

sequence SE5I132
  E5I132D0
  E101I132D1
end SE5I132

sequence SE5I133
  E5I133D0
  E101I133D1
end SE5I133

sequence SE5I134
  E5I134D0
  E101I134D1
end SE5I134

sequence SE5I135
  E5I135D0
  E101I135D1
end SE5I135

sequence SE5I136
  E5I136D0
  E101I136D1
end SE5I136

sequence SE5I137
  E5I137D0
  E101I137D1
end SE5I137

sequence SE5I138
  E5I138D0
  E101I138D1
end SE5I138

sequence SE5I139
  E5I139D0
  E101I139D1
end SE5I139

sequence SE5I140
  E5I140D0
  E101I140D1
end SE5I140

sequence SE5I141
  E5I141D0
  E101I141D1
end SE5I141

sequence SE5I142
  E5I142D0
  E101I142D1
end SE5I142

sequence SE5I143
  E5I143D0
  E101I143D1
end SE5I143

sequence SE5I144
  E5I144D0
  E100I144D1
end SE5I144

sequence SE5I145
  E5I145D0
  E100I145D1
end SE5I145

sequence SE5I146
  E5I146D0
  E100I146D1
end SE5I146

sequence SE5I147
  E5I147D0
  E100I147D1
end SE5I147

sequence SE5I148
  E5I148D0
  E100I148D1
end SE5I148

sequence SE5I149
  E5I149D0
  E100I149D1
end SE5I149

sequence SE5I150
  E5I150D0
  E100I150D1
end SE5I150

sequence SE5I151
  E5I151D0
  E100I151D1
end SE5I151

sequence SE5I152
  E5I152D0
  E100I152D1
end SE5I152

sequence SE5I153
  E5I153D0
  E100I153D1
end SE5I153

sequence SE5I154
  E5I154D0
  E100I154D1
end SE5I154

sequence SE5I155
  E5I155D0
  E100I155D1
end SE5I155

sequence SE5I156
  E5I156D0
  E100I156D1
end SE5I156

sequence SE5I157
  E5I157D0
  E100I157D1
end SE5I157

sequence SE5I158
  E5I158D0
  E100I158D1
end SE5I158

sequence SE5I159
  E5I159D0
  E100I159D1
end SE5I159

sequence SE5I160
  E5I160D0
  E100I160D1
end SE5I160

sequence SE5I161
  E5I161D0
  E100I161D1
end SE5I161

sequence SE5I162
  E5I162D0
  E100I162D1
end SE5I162

sequence SE5I163
  E5I163D0
  E100I163D1
end SE5I163

sequence SE5I164
  E5I164D0
  E100I164D1
end SE5I164

sequence SE5I165
  E5I165D0
  E100I165D1
end SE5I165

sequence SE5I166
  E5I166D0
  E100I166D1
end SE5I166

sequence SE5I167
  E5I167D0
  E100I167D1
end SE5I167

sequence SE5I168
  E5I168D0
  E100I168D1
end SE5I168

sequence SE5I169
  E5I169D0
  E101I169D1
end SE5I169

sequence SE5I170
  E5I170D0
  E101I170D1
end SE5I170

sequence SE5I171
  E5I171D0
  E101I171D1
end SE5I171

sequence SE5I172
  E5I172D0
  E101I172D1
end SE5I172

sequence SE5I173
  E5I173D0
  E101I173D1
end SE5I173

sequence SE5I174
  E5I174D0
  E101I174D1
end SE5I174

sequence SE5I175
  E5I175D0
  E101I175D1
end SE5I175

sequence SE5I176
  E5I176D0
  E101I176D1
end SE5I176

sequence SE5I177
  E5I177D0
  E101I177D1
end SE5I177

sequence SE5I178
  E5I178D0
  E101I178D1
end SE5I178

sequence SE5I179
  E5I179D0
  E101I179D1
end SE5I179

sequence SE5I180
  E5I180D0
  E101I180D1
end SE5I180

